@startuml
|Администратор|
start
:Администратор ввел данные сотрудника;
:Администратор выбрал роль сотрудника;
:Администратор создал учетную запись сотрудника;
:Сотрудник добавлен в общий список персонала;
if (Новый сотрудник администратор?) then (Да)
    :Сотрудник имеет полный доступ к управлению платформы;
else (Нет)
    :Сотрудник имеет возможность читать новости,
    пользоваться основной информацией портала;
endif
:Администратор ввел данные департамента;
:Администратор добавил необходимых сотрудников;
:Создан новый департамент;
if (Добавлен лишний сотрудник?) then (Да)
    :Выбрать сотрудника;
    :Удалить из департамента;
else (Нет)
endif
if (Необхоимо добавить нового сотрудника?) then (Да)
    :Выбрать сотрудника;
    :Добавить в департамент;
else (Нет)
endif
:Данные департамента обновлены;
stop